FROM python:3.13-slim-bookworm

WORKDIR /app

RUN pip install --no-cache-dir "mlflow==3.6.0"

# Copy your local registry state into the image
# Assumes mlflow.db and mlruns are in repo root.
COPY mlflow.db /app/mlflow.db
COPY mlruns /app/mlruns

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "/app/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"] 

